spring:
  datasource:
    driver-class-name: org.h2.Driver # db name
    url: jdbc:h2:~/bookdb # ~/ = home directory
    username: sa
    password: 1234
  h2:
    console:
      enabled: true # I want to see it on browser (console)
      path: /h2-console # localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: create #
      show-sql: true # what sql query is being made